---
- hosts: all
  become: true
  vars:
    mysql_package_name: Percona-Server-server-56

  roles:
    - devenv-yum
    - devenv-base
    - repo-percona
    - name: elasticsearch
      es_instance_name: "es-dev1"
      es_config: {
        http.host: 0.0.0.0,
        http.port: 9200,
        transport.tcp.port: 9300,

        index.query.bool.max_clause_count: 16384    # devdocs specifies 10024 for catalogs with > 40k SKUs, need higher
      }

  tasks:
    - name: Upload /etc/
      copy:
        src: files/db/etc/
        dest: /etc/

    - name: Uploading init-mysql.sh
      template:
        src: init-mysql.sh
        dest: /usr/local/bin/init-mysql.sh
        owner: root
        group: root
        mode: 0700

    - name: Initializing mysql data
      command: /usr/local/bin/init-mysql.sh
      args:
        creates: /var/lib/mysql/ibdata1

    # Ensures Percona is installed when init procedure isn't needed
    - name: Installing Percona server
      package:
        name: "{{ mysql_package_name }}"
        state: present

    - name: Starting mysql service
      service:
        name: mysql
        state: started
        enabled: no     # no auto-starting after reboot (i.e. halt, up); provisioner starts it after data is mounted

    - name: Install python-mysqldb
      package:
        name: MySQL-python
        state: present

    - name: Configuring mysql root user
      mysql_user:
        user: root
        host: "{{ item }}"
        priv: "*.*:ALL,GRANT"
      with_items:
        - localhost
        - dev-host
        - dev-web70
        - dev-web56
        - dev-db
