---
- name: install npm
  package:
    name: npm

- name: configure npm cache
  lineinfile:
    line: "{{ item }}"
    dest: /usr/etc/npmrc
    create: yes
  with_items:
    - cache = /var/cache/npm
    - cache-min = 86400

# fix npm install problem by overwriting symlink with copy of linked version
- block:
    - name: lookup node_modules/inherits
      command: readlink -f /usr/lib/node_modules/inherits
      register: inherits
      changed_when: false
    
    - name: remove node_modules/inherits link
      file:
        path: /usr/lib/node_modules/inherits
        state: absent
      when: inherits.stdout != '/usr/lib/node_modules/inherits'
    
    - name: copy node_modules/inherits from src
      command: cp -R "{{ inherits.stdout }}" /usr/lib/node_modules/inherits
      when: inherits.stdout != '/usr/lib/node_modules/inherits'
